# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orpheus/v1/common.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'orpheus/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17orpheus/v1/common.proto\x12\norpheus.v1\"%\n\x04Page\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\"\x17\n\tTenantRef\x12\n\n\x02id\x18\x01 \x01(\t*\xa0\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11JOB_STATUS_QUEUED\x10\x01\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n\x11JOB_STATUS_FAILED\x10\x04\x12\x17\n\x13JOB_STATUS_CANCELED\x10\x05*j\n\x07JobType\x12\x18\n\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19JOB_TYPE_EXTRACT_METADATA\x10\x01\x12\x12\n\x0eJOB_TYPE_PROBE\x10\x02\x12\x12\n\x0eJOB_TYPE_SLICE\x10\x03\x42:Z8github.com/orpheus/api/internal/gen/orpheus/v1;orpheusv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orpheus.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/orpheus/api/internal/gen/orpheus/v1;orpheusv1'
  _globals['_JOBSTATUS']._serialized_start=104
  _globals['_JOBSTATUS']._serialized_end=264
  _globals['_JOBTYPE']._serialized_start=266
  _globals['_JOBTYPE']._serialized_end=372
  _globals['_PAGE']._serialized_start=39
  _globals['_PAGE']._serialized_end=76
  _globals['_TENANTREF']._serialized_start=78
  _globals['_TENANTREF']._serialized_end=101
# @@protoc_insertion_point(module_scope)
