# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orpheus.v1 import jobs_pb2 as orpheus_dot_v1_dot_jobs__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orpheus/v1/jobs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """WorkerService is the control-plane RPC between the Go API and the
    Python worker process. It is NOT the queue — Arq (Redis) is the
    queue. This service exists so the API can ask the worker for
    live status without going through Postgres.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/orpheus.v1.WorkerService/Ping',
                request_serializer=orpheus_dot_v1_dot_jobs__pb2.PingRequest.SerializeToString,
                response_deserializer=orpheus_dot_v1_dot_jobs__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/orpheus.v1.WorkerService/GetJobStatus',
                request_serializer=orpheus_dot_v1_dot_jobs__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=orpheus_dot_v1_dot_jobs__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService is the control-plane RPC between the Go API and the
    Python worker process. It is NOT the queue — Arq (Redis) is the
    queue. This service exists so the API can ask the worker for
    live status without going through Postgres.
    """

    def Ping(self, request, context):
        """Ping is the liveness check. Returns the worker's version + a
        list of the job_types it knows how to handle. Used by the
        Go API's /ready probe in Phase 3+.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """GetJobStatus asks the worker for the live status of a job
        it has pulled from Arq. The worker may return JOB_STATUS_QUEUED
        if it has not yet claimed the job — that is the same value the
        Postgres row carries, so the API can choose to fall back to
        the row when the worker is unreachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=orpheus_dot_v1_dot_jobs__pb2.PingRequest.FromString,
                    response_serializer=orpheus_dot_v1_dot_jobs__pb2.PingResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=orpheus_dot_v1_dot_jobs__pb2.GetJobStatusRequest.FromString,
                    response_serializer=orpheus_dot_v1_dot_jobs__pb2.GetJobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orpheus.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orpheus.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService is the control-plane RPC between the Go API and the
    Python worker process. It is NOT the queue — Arq (Redis) is the
    queue. This service exists so the API can ask the worker for
    live status without going through Postgres.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orpheus.v1.WorkerService/Ping',
            orpheus_dot_v1_dot_jobs__pb2.PingRequest.SerializeToString,
            orpheus_dot_v1_dot_jobs__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orpheus.v1.WorkerService/GetJobStatus',
            orpheus_dot_v1_dot_jobs__pb2.GetJobStatusRequest.SerializeToString,
            orpheus_dot_v1_dot_jobs__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
