# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orpheus/v1/jobs.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'orpheus/v1/jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from orpheus.v1 import common_pb2 as orpheus_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15orpheus/v1/jobs.proto\x12\norpheus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17orpheus/v1/common.proto\"-\n\x0cProcessorRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\xae\x03\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x03org\x18\x02 \x01(\x0b\x32\x15.orpheus.v1.TenantRef\x12\x13\n\x0b\x61rtifact_id\x18\x03 \x01(\t\x12+\n\tprocessor\x18\x04 \x01(\x0b\x32\x18.orpheus.v1.ProcessorRef\x12%\n\x08job_type\x18\x05 \x01(\x0e\x32\x13.orpheus.v1.JobType\x12%\n\x06status\x18\x06 \x01(\x0e\x32\x15.orpheus.v1.JobStatus\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nstarted_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63ompleted_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61ttempts\x18\x0b \x01(\x05\x12\x13\n\x0bmax_retries\x18\x0c \x01(\x05\"\r\n\x0bPingRequest\"X\n\x0cPingResponse\x12\x16\n\x0eworker_version\x18\x01 \x01(\t\x12\x30\n\x13supported_job_types\x18\x02 \x03(\x0e\x32\x13.orpheus.v1.JobType\"%\n\x13GetJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x94\x01\n\x14GetJobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.orpheus.v1.JobStatus\x12\x15\n\rstatus_detail\x18\x03 \x01(\t\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x9d\x01\n\rWorkerService\x12\x39\n\x04Ping\x12\x17.orpheus.v1.PingRequest\x1a\x18.orpheus.v1.PingResponse\x12Q\n\x0cGetJobStatus\x12\x1f.orpheus.v1.GetJobStatusRequest\x1a .orpheus.v1.GetJobStatusResponseB:Z8github.com/orpheus/api/internal/gen/orpheus/v1;orpheusv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orpheus.v1.jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/orpheus/api/internal/gen/orpheus/v1;orpheusv1'
  _globals['_PROCESSORREF']._serialized_start=95
  _globals['_PROCESSORREF']._serialized_end=140
  _globals['_JOB']._serialized_start=143
  _globals['_JOB']._serialized_end=573
  _globals['_PINGREQUEST']._serialized_start=575
  _globals['_PINGREQUEST']._serialized_end=588
  _globals['_PINGRESPONSE']._serialized_start=590
  _globals['_PINGRESPONSE']._serialized_end=678
  _globals['_GETJOBSTATUSREQUEST']._serialized_start=680
  _globals['_GETJOBSTATUSREQUEST']._serialized_end=717
  _globals['_GETJOBSTATUSRESPONSE']._serialized_start=720
  _globals['_GETJOBSTATUSRESPONSE']._serialized_end=868
  _globals['_WORKERSERVICE']._serialized_start=871
  _globals['_WORKERSERVICE']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
