package auth

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/alexedwards/argon2id"
)

// API key shape
//
// The full key as presented to the API is:
//
//	ak_live_<32 random bytes, base62-encoded>
//
// e.g. `ak_live_4f9c2d1e8a...` (39 chars after the "ak_live_"
// prefix, total 47 chars). The first 9 characters
// (`ak_live_X` where X is the first base62 char of the secret) are
// stored verbatim in the api_keys.prefix column and used as the
// lookup key. Storing a short, non-secret prefix keeps the index
// small while still giving us enough entropy to make prefix-only
// lookups unambiguous in practice.

const (
	apiKeyPrefix    = "ak_"
	apiKeyPrefixLen = 9 // "ak_live_X" — short, indexable
	apiKeyMinLength = apiKeyPrefixLen + 1
)

// APIKeyRecord is the subset of the api_keys row the auth layer
// needs. The real *db.ApiKey generated by sqlc satisfies this shape
// field-for-field, so a *db.DB can be passed in directly via
// [NewAPIKeyValidatorFromDB].
type APIKeyRecord struct {
	ID           string
	OrgID        string
	HashedSecret string
	Prefix       string
	Scopes       []string
	RevokedAt    *string // nil if active; *string so tests can use a literal
}

// APIKeyLookup is the minimum surface the auth layer needs from the
// database. *db.DB (with sqlc-generated GetAPIKeyByPrefix) satisfies
// this; tests can supply an in-memory stub.
type APIKeyLookup interface {
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (APIKeyRecord, error)
}

// APIKeyValidator validates X-API-Key values against the api_keys
// table. The validator is safe for concurrent use by many goroutines.
type APIKeyValidator struct {
	lookup APIKeyLookup
}

// NewAPIKeyValidator returns a validator backed by lookup.
func NewAPIKeyValidator(lookup APIKeyLookup) *APIKeyValidator {
	return &APIKeyValidator{lookup: lookup}
}

// Verify looks up fullKey by its prefix, then verifies the full
// secret against the stored Argon2id hash. Returns a Principal with
// the resolved org_id and the key's scopes (which double as the
// key's roles for authorization).
func (v *APIKeyValidator) Verify(ctx context.Context, fullKey string) (*Principal, error) {
	if !strings.HasPrefix(fullKey, apiKeyPrefix) {
		return nil, errors.New("auth.apikey: invalid format")
	}
	if len(fullKey) < apiKeyMinLength {
		return nil, errors.New("auth.apikey: invalid format")
	}

	prefix := fullKey[:apiKeyPrefixLen]

	key, err := v.lookup.GetAPIKeyByPrefix(ctx, prefix)
	if err != nil {
		return nil, fmt.Errorf("auth.apikey.lookup: %w", err)
	}
	if key.RevokedAt != nil {
		return nil, errors.New("auth.apikey: revoked")
	}

	ok, err := argon2id.ComparePasswordAndHash(fullKey, key.HashedSecret)
	if err != nil {
		return nil, fmt.Errorf("auth.apikey.verify_hash: %w", err)
	}
	if !ok {
		return nil, errors.New("auth.apikey: invalid")
	}

	return &Principal{
		OrgID:    key.OrgID,
		APIKeyID: key.ID,
		Roles:    key.Scopes,
	}, nil
}
