package auth

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/alexedwards/argon2id"
)

// verifyCacheTTL is how long a successful Argon2id verification is
// remembered. Argon2id is deliberately CPU/memory-hard (~tens of ms and
// 64 MiB per call), so running it on EVERY request caps throughput at a
// few dozen req/s and is a CPU-exhaustion DoS vector. We cache the
// *successful* verification (never failures) for a short window; the
// fast, indexed prefix lookup still runs every request, so revocation
// takes effect within one lookup regardless of the cache.
const (
	verifyCacheTTL     = 5 * time.Minute
	verifyCacheMaxSize = 10000
)

// verifyCache is a tiny TTL cache of proven (presented-key, stored-hash)
// pairs. The key is a SHA-256 of the full key + stored hash, so the
// plaintext is never stored and rotating the key (new hash) misses.
type verifyCache struct {
	mu  sync.RWMutex
	m   map[string]time.Time // cacheKey -> expiry
	ttl time.Duration
	max int
}

func newVerifyCache() *verifyCache {
	return &verifyCache{m: make(map[string]time.Time), ttl: verifyCacheTTL, max: verifyCacheMaxSize}
}

func (c *verifyCache) valid(key string) bool {
	c.mu.RLock()
	exp, ok := c.m[key]
	c.mu.RUnlock()
	return ok && time.Now().Before(exp)
}

func (c *verifyCache) store(key string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	// Crude bound: flush wholesale when full. Simpler than an LRU and
	// fine for a short-TTL positive cache — entries expire quickly anyway.
	if len(c.m) >= c.max {
		c.m = make(map[string]time.Time, c.max)
	}
	c.m[key] = time.Now().Add(c.ttl)
}

func verifyCacheKey(fullKey, hashedSecret string) string {
	sum := sha256.Sum256([]byte(fullKey + "\x00" + hashedSecret))
	return hex.EncodeToString(sum[:])
}

// API key shape
//
// The full key as presented to the API is:
//
//	ak_live_<32 random bytes, base62-encoded>
//
// e.g. `ak_live_4f9c2d1e8a...` (39 chars after the "ak_live_"
// prefix, total 47 chars). The first 9 characters
// (`ak_live_X` where X is the first base62 char of the secret) are
// stored verbatim in the api_keys.prefix column and used as the
// lookup key. Storing a short, non-secret prefix keeps the index
// small while still giving us enough entropy to make prefix-only
// lookups unambiguous in practice.

const (
	apiKeyPrefix    = "ak_"
	apiKeyPrefixLen = 9 // "ak_live_X" — short, indexable
	apiKeyMinLength = apiKeyPrefixLen + 1
)

// APIKeyRecord is the subset of the api_keys row the auth layer
// needs. The real *db.ApiKey generated by sqlc satisfies this shape
// field-for-field, so a *db.DB can be passed in directly via
// [NewAPIKeyValidatorFromDB].
type APIKeyRecord struct {
	ID           string
	OrgID        string
	HashedSecret string
	Prefix       string
	Scopes       []string
	RevokedAt    *string // nil if active; *string so tests can use a literal
}

// APIKeyLookup is the minimum surface the auth layer needs from the
// database. *db.DB satisfies this; tests can supply an in-memory stub.
//
// It returns ALL active keys sharing a prefix, not one: the stored prefix is
// only "ak_live_" + one base64 char (see apiKeyPrefixLen), so collisions are
// expected and the validator must Argon2-verify the presented secret against
// every candidate. Returning a single row (LIMIT 1) makes auth fail whenever a
// different key with the same prefix is picked.
type APIKeyLookup interface {
	GetAPIKeysByPrefix(ctx context.Context, prefix string) ([]APIKeyRecord, error)
}

// APIKeyValidator validates X-API-Key values against the api_keys
// table. The validator is safe for concurrent use by many goroutines.
type APIKeyValidator struct {
	lookup APIKeyLookup
	cache  *verifyCache
}

// NewAPIKeyValidator returns a validator backed by lookup.
func NewAPIKeyValidator(lookup APIKeyLookup) *APIKeyValidator {
	return &APIKeyValidator{lookup: lookup, cache: newVerifyCache()}
}

// Verify looks up fullKey by its prefix, then verifies the full
// secret against the stored Argon2id hash. Returns a Principal with
// the resolved org_id and the key's scopes (which double as the
// key's roles for authorization).
func (v *APIKeyValidator) Verify(ctx context.Context, fullKey string) (*Principal, error) {
	if !strings.HasPrefix(fullKey, apiKeyPrefix) {
		return nil, errors.New("auth.apikey: invalid format")
	}
	if len(fullKey) < apiKeyMinLength {
		return nil, errors.New("auth.apikey: invalid format")
	}

	prefix := fullKey[:apiKeyPrefixLen]

	keys, err := v.lookup.GetAPIKeysByPrefix(ctx, prefix)
	if err != nil {
		return nil, fmt.Errorf("auth.apikey.lookup: %w", err)
	}
	if len(keys) == 0 {
		return nil, errors.New("auth.apikey: not_found")
	}

	// The prefix is low-entropy, so multiple active keys can share it. Find the
	// candidate whose stored hash matches the presented secret; only that key's
	// identity matters. Revocation always beats the verify cache (the fresh
	// lookup normally filters revoked rows, but this keeps a just-revoked,
	// still-cached key out).
	sawRevoked := false
	for i := range keys {
		key := keys[i]

		cacheKey := ""
		if v.cache != nil {
			cacheKey = verifyCacheKey(fullKey, key.HashedSecret)
			if v.cache.valid(cacheKey) {
				if key.RevokedAt != nil {
					return nil, errors.New("auth.apikey: revoked")
				}
				return &Principal{OrgID: key.OrgID, APIKeyID: key.ID, Roles: key.Scopes}, nil
			}
		}

		// Don't spend an Argon2 compare (or trust its hash) on a revoked row.
		if key.RevokedAt != nil {
			sawRevoked = true
			continue
		}

		ok, err := argon2id.ComparePasswordAndHash(fullKey, key.HashedSecret)
		if err != nil {
			return nil, fmt.Errorf("auth.apikey.verify_hash: %w", err)
		}
		if !ok {
			continue // a colliding-prefix key, not this one
		}
		if v.cache != nil {
			v.cache.store(cacheKey)
		}
		return &Principal{OrgID: key.OrgID, APIKeyID: key.ID, Roles: key.Scopes}, nil
	}

	// No live candidate matched. If every candidate for this prefix was
	// revoked, surface that; otherwise the secret is simply wrong.
	if sawRevoked {
		return nil, errors.New("auth.apikey: revoked")
	}
	return nil, errors.New("auth.apikey: invalid")
}
